/*
===============================================================================
		Seller Performance
===============================================================================
1. Business objective:
    Analyze high-performing sellers (total revenue > $1,000) to evaluate 
    their revenue, order volume, and identify their primary product category 
    by revenue share for targeted merchant support.

2. Key metrics:
    - seller_id: unique identifier for the seller
    - total_orders_count: total number of unique orders fulfilled by the seller
    - total_revenue: total monetary value generated by the seller
    - top_category_name: product category driving the highest revenue for the seller

3. Technical highlights:
    - Common Table Expressions (CTE) for pre-aggregating seller metrics
    - LATERAL JOIN to extract the top-1 revenue-generating product category
    - HAVING clause to filter sellers exceeding $1,000 in total sales
    - COALESCE and ROUND for null handling and clean formatting
===============================================================================
*/


WITH seller_metrics AS (SELECT osd.seller_id,
                               COUNT(DISTINCT ooid.order_id) AS total_orders_count,
                               COALESCE(SUM(ooid.price), 0)  AS total_revenue
                        FROM olist_sellers_dataset osd
                                 JOIN olist_order_items_dataset ooid
                                      ON
                                          ooid.seller_id = osd.seller_id
                        GROUP BY osd.seller_id
                        HAVING COALESCE(SUM(ooid.price), 0) > 1000)

SELECT sm.seller_id,
       sm.total_orders_count,
       ROUND(sm.total_revenue::NUMERIC, 2)                           AS total_revenue,
       COALESCE(top_category.product_category_name, 'Uncategorised') AS top_category_name
FROM seller_metrics sm
         LEFT JOIN LATERAL (
    SELECT opd_sub.product_category_name
    FROM olist_order_items_dataset ooid_sub
             LEFT JOIN olist_products_dataset opd_sub ON
        ooid_sub.product_id = opd_sub.product_id
    WHERE ooid_sub.seller_id = sm.seller_id
    GROUP BY opd_sub.product_category_name
    ORDER BY SUM(ooid_sub.price) DESC
    LIMIT 1) top_category ON
    TRUE
ORDER BY sm.total_revenue DESC;

